name: pet_store_bloc
description: A new Flutter application.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  built_collection: ^4.3.2
  dio: ^3.0.9
  flutter:
    sdk: flutter
  openapi:
    path: api
  wakelock: ^0.1.4+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
flutter:
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
